/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AlertDialog: typeof import('./src/components/AlertDialog.vue')['default']
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    AppNavigation: typeof import('./src/components/AppNavigation.vue')['default']
    AppProgress: typeof import('./src/components/AppProgress.vue')['default']
    AppSnackbar: typeof import('./src/components/AppSnackbar.vue')['default']
    ConfirmationDialog: typeof import('./src/components/ConfirmationDialog.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    LoginForm: typeof import('./src/components/Forms/LoginForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TextField: typeof import('./src/components/Forms/TextField.vue')['default']
  }
}
