services:
  client-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: client-service
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
    stdin_open: true
    tty: true
    entrypoint: ["sh", "/usr/local/bin/entrypoint.sh"]
    ports:
      - "3000:3000"